/**
 * Generated by https://www.convertjson.com/yaml-to-json.htm and https://app.quicktype.io/
 * then: main obj is DictEntriesFile, ErtClass is Ert, DictEntr usages are Forras, DictEntr removed
 */

/**
 * Dictionary Entries File
 */
export interface DictEntriesFile {
    /**
     * utolsó módosítás dátuma ilyen formában 2020-05-15
     */
    datum:  string;
    forras: Forras;
    /**
     * szótári címszavanként 1-1 elem
     */
    szavak: Szavak[];
}

export interface Forras {
    /**
     * ha a forrás kötete vagy része több fejezetes, hivatkozás a fejezetre
     */
    fejezet?: number | string;
    /**
     * ha a forrás több kötetes, hivatkozás a kötetre
     */
    kotet?: number | string;
    /**
     * a szavak forrásának megnevezése rövid hivatkozási névvel, pl. Vinód, Pratap
     */
    nev: string;
    /**
     * ha a forrás kötete több részes, hivatkozás a részre
     */
    resz?: number | string;
}

export interface Szavak {
    /**
     * alternatív írásmódok listája
     */
    alt?: string[];
    /**
     * etimológiai forrás szó vagy szavak
     */
    etim?: string;
    /**
     * a címszóhoz tartozó fordítások listája, mint a szótárakban elkülönített a számozott
     * jelentések
     */
    ford: Ford[];
    /**
     * hivatkozás másik címszóra
     */
    lasd?: string;
    /**
     * ugyanennek a szónak korábbi verziójához nem hozzátenni akarunk, hanem lecserélni;
     * a törlendő és az új indexeket kell felsorolni, ebben a formában: 1,3,4=2, ahol
     * a megmaradó indexek felfelé tömörödnek, és az új index abba a sorba szúródik be
     */
    lecserel?: string;
    /**
     * a szótári címszó sorszáma, ha alakilag azonos szavak vannak teljesen más értelemmel
     */
    sorsz?: number;
    /**
     * nyelv(ek) rövidítése, amiből a szó eredetileg származik, pl. S, P, A, Pr, Pt, E
     */
    szarm?: string;
    /**
     * a szótári címszó
     */
    szo: string;
}

export interface Ford {
    /**
     * antonímák a fordításhoz
     */
    ant?: string[];
    /**
     * a jelentéshez tartozó többféle fordítás, értelmezés
     */
    ert: Array<Ert | string>;
    /**
     * ha nem azonos a fájlban megadott forrással, vagy egy fordításhoz
     * több forrás tartozik
     */
    forras?: Forras[];
    /**
     * forrás azonosítása az adatbázisban
     */
    forras_id?: string;
    /**
     * a címszóhoz tartozó kifejezési formula; ~ használható
     */
    kif?: any;
    /**
     * a fordítás lexikális besorolása a Longman Lexicon of Contemporary English
     * szisztémája szerint
     */
    lex?: string;
    /**
     * szófaj vagy más nyelvtani utalások; ugyanaz szerepelhet több fordításhoz is
     */
    nyt?: string;
    /**
     * a fordításhoz tartozó példamondatok vagy kifejezések
     */
    pl?: Pl[];
    /**
     * szinonímák a fordításhoz
     */
    szin?: string[];
    /**
     * a szó nyelvtani változatai, nem szabályos ragozás, stb.
     */
    var?: Var[];
}

/**
 * fordítás bővített információval együtt
 */
export interface Ert {
    /**
     * egyéb információ a jelentéssel kapcsolatban
     */
    megj?: string;
    /**
     * nyelvtani utalások
     */
    nyt?: string;
    /**
     * a fordítás
     */
    szo: string;
}

export interface Pl {
    /**
     * mondat vagy kifejezés az eredeti nyelven
     */
    ered: string;
    /**
     * fordítás a példához
     */
    ford?: string;
    /**
     * a példa forrása
     */
    forras?: Forras;
}

export interface Var {
    /**
     * a változat formai alakja
     */
    alak?: string;
    /**
     * a változat nyelvtani tartalma, pl. tbsz
     */
    tipus?: string;
}
